dist: trusty
language: generic

script:
  - set -eo pipefail
  - sudo groupadd --system lxd
  - sudo usermod -a -G lxd $USER
  - sudo apt-get -qq update
  - sudo apt-get --yes install snapd
  - sudo snap install lxd
  - sudo lxd waitready
  - printf 'n\ny\ndefault\ndir\nn\ny\nlxdbr0\nauto\nauto\ny\nall\n\ny\nn\n' | sudo lxd init
  - sudo lxd.lxc profile copy default travis
  - sudo lxd.lxc profile set travis security.privileged true
  - sudo lxd.lxc launch images:alpine/3.5 alpine --profile travis
  - sudo lxd.lxc config device add alpine travis disk source="$PWD" path=/travis
  - sudo lxd.lxc exec alpine -- ls -al /travis
